// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxjfgjftbgtusweolqmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4amZnamZ0Ymd0dXN3ZW9scW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzI4NzAsImV4cCI6MjA2NDQ0ODg3MH0.CfLLmtn8hXRD6J9a6JgsJ_PFgHYYuKe4dP8ZbGepk2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);