// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfxvqvvtlujoxahqfrcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmeHZxdnZ0bHVqb3hhaHFmcmNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODE2OTAsImV4cCI6MjA2OTc1NzY5MH0.Xom_Gn3q27S2IqY2eRGjVlilBhuuIT4EFaunhUjZ-2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});